
name: php_cache
version: 0.0.1
language: php
description: "本插件主要缓存依赖包，已有缓存时直接使用缓存，提高构建效率"
public: true
tags:
  - php
  - cache
inputs:
  - name: FLOW_ENABLE_CACHE
    editable: true
    options:
      - TRUE=true
      - FALSE=false
  - name: FLOW_VERSION
    editable: false
  - name: FLOW_PROJECT_ID
    editable: false
outputs:
  - name: FLOW_ENABLE_CACHE
script_path: ./run.sh  
  
template: |  
  
  
